### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Klayfez** [HarvelsX/Sugar#6]
I use the sugar 3.3.4 for 1.19.3 modpack and everything is fine with it. But with sugar 3.3.4.1, what happens in the video (sorry for the quality, reduced for the file size) is happening on all servers and in single worlds. I also noticed that Fabulously Optimized and Simply Optimized also behave this way.
video:
deleted
logs:
https://paste.atlauncher.com/view/c75209fd-4f38-4c3b-9594-e84a25e69255

PS: I contacted ATLauncher support, they could not help me, they offered to write to you
And I write through an interpreter, so in some cases there may be misunderstandings

**Comment by HarvelsX** [comment]
Hello! Unfortunately, there is not enough information to talk about anything specific. Please provide the last couple of crash-logs so that I can determine the problem.
